### ISSUE TITLE
Request for getColorAtUV

### ISSUE THREAD

**Issue by MartinSenovsky** [pshtif/Genome2D-ContextFlash#11]
In:
Genome2D-ContextFlash/src/com/genome2d/textures/GTexture.hx

function getAlphaAtUV(p_u:Float, p_v:Float):Float  already gets pixel's rbga, but returns only the alpha part, please add getColorAtUV that will return all the color components.

**Comment by pshtif** [comment]
Added getColorAtUv and changed getAlphaAtUv to UInt as well since float was a little misleading since the return value isn't normalized.
