### ISSUE TITLE
GTexture not match to its constructor parameters

### ISSUE THREAD

**Issue by gNikro** [pshtif/Genome2D-ContextFlash#6]
Example:

I have BitmapData and i want create texture from bitmapData 

```
var bitmapData:BitmapData = new BitmapData(256, 128, true, 0x0);
GTextureManager.createTexture("test", bitmapData:BitmapData , 1, false, Context3DTextureFormat.COMPRESSED_ALPHA);//or COMPRESSED, RGBA_HALF_FLOAT
```

What we expect?
We expect to get Texture with COMPRESSED_ALPHA content
//NOTE: flash player 16 + can upload compressed textures in runtime

What we get?
RectangleTexture with no one known format probably RGBA

That caused of this:
https://github.com/pshtif/Genome2D-ContextFlash/blob/master/src/com/genome2d/textures/GTexture.hx#L106

Also there 
https://github.com/pshtif/Genome2D-ContextCommon/blob/master/src/com/genome2d/textures/GTextureManager.hx#L82

texture format is just ignored and not set to texture

Then there is hardcoded default texture format
https://github.com/pshtif/Genome2D-ContextCommon/blob/master/src/com/genome2d/textures/GTextureBase.hx#L325

So its mean constructor arg texture format even didn't used and i always get BGRA texture only

So its unable to control what i will get while i create texture and no option to turn off that mechanics

**Comment by pshtif** [comment]
Thanks, this got probably missed due to the Texture refactoring that was done in 1.1 version. Kind of strange that no one actually spotted it yet. We personally don't use textured formats in any of our projects internally. Anyway thanks for reporting and will be resolved.

**Comment by pshtif** [comment]
Fixed although not tested even though it should be straightforward fix.

Added format paramter to the GTexture constructor and propagate it from the GTextureManager accordingly.

**Comment by gNikro** [comment]
rectangle textures supports only BGRA, BGR_PACKED, BGRA_PACKED. So GTextureBase.usesRectangle should check format if it COMPRESSES/COMPRESSED_ALPHA return false

Also u should set g2d_atfType for textures based on bitmap with COMPRESSED formats

**Comment by pshtif** [comment]
Thanks will look into that.
