### ISSUE TITLE
Error with fast memory

### ISSUE THREAD

**Issue by gNikro** [pshtif/Genome2D-ContextFlash#7]
Fast memory select ByteArray only once in constructor.
In my app i using FastMemory aswell as genome.
When i switch ApplicationDomain to some byteArray genome never switch it back to its own "Buffer".
When byteArray that i pass to ApplicationDomain is smaller then genome need to render scene it throw RangeError at Draw

Solution: Check ApplicationDomain on each prerender phase and set it to DomainMemory if its neccessary

https://github.com/pshtif/Genome2D-ContextFlash/blob/master/src/com/genome2d/context/stage3d/GStage3DContext.hx#L256

**Comment by pshtif** [comment]
Genome2D had this build in but since the switching was too slow and in most cases not worth it I removed it. Maybe I can add it based on some opt-in parameter. Anyway you can also create a pull request for this if you already implemented it and want it as part of the code base.
