### ISSUE TITLE
GTextureManager.craeteSubTexture works bad

### ISSUE THREAD

**Issue by gNikro** [pshtif/Genome2D-ContextFlash#8]
https://github.com/pshtif/Genome2D-ContextCommon/blob/73646ae29da9d2eba8fe80ab1d9f2ad39a1c2fb2/src/com/genome2d/textures/GTextureManager.hx#L131

Texture atlas ID and sub texture ID is separate by "_" that is really bad, why?
Many assets is using same dillemiter for example in our project we have
albion_water_light.swf
and 
albion_water_light_2.swf

I conver that swfs to atlases and animations, so every clip will be sub texture of that swf atlas.
When we parse swf movieClips, shapes, etc... ids appear in order from 1 to N+1

So when i parse albion_water_light one of its sub textures have id 2 and it will be looks like
albion_water_light_2

Then when i try to create atlas with albion_water_light_2 for albion_water_light_2.swf i catch error. And really cant even image frm where this error appear :)

So using "_" as dillemiter by default is not the best idea because almost everyone use that for assets, sprites linkage naming, etc...

**Comment by pshtif** [comment]
You can create subtextures without the parent ID prefix, not sure which version are you using but for quite some time there is a paramter in createSubTexture method called p_prefixParentId true by default which tells Genome2D to prefix subtexture id with parentId_

Anyway maybe I will introduce a delimeter parameter to specify the type of delimeter you want Genome2D to use.
